apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-business-services
  namespace: dev
spec:
  podSelector:
    matchLabels:
      tier: business
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
    ports:
    - protocol: TCP
      port: 8081  # user-service
    - protocol: TCP
      port: 8082  # product-service
    - protocol: TCP
      port: 8083  # favourite-service
    - protocol: TCP
      port: 8084  # order-service
    - protocol: TCP
      port: 8085  # shipping-service
    - protocol: TCP
      port: 8086  # payment-service
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: service-discovery
    ports:
    - protocol: TCP
      port: 8761
  - to:
    - podSelector:
        matchLabels:
          app: cloud-config-server
    ports:
    - protocol: TCP
      port: 8888
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

